### PR TITLE
Fix 92 gs integration tests

### LINKED ISSUE #92: GS backend Fails List tests in backend integration tests
`GOOGLE_APPLICATION_CREDENTIALS=~/.gsutil/account.json VFS_INTEGRATION_LOCATIONS="gs://<INSERT BUCKET NAME>/vfs_test/" go test -count=1 -tags=vfsintegration -v ./backend/testsuite/` produces: 

```go
=== RUN   TestVFS
=== RUN   TestVFS/TestScheme
************** TESTING scheme: gs **************
****** testing vfs.FileSystem ******
****** testing vfs.Location ******
!!!!!! testing gs-specific List() tests !!!!!!
    backend_integration_test.go:401:
        	Error Trace:	backend_integration_test.go:401
        	            				backend_integration_test.go:118
        	Error:      	Not equal:
        	            	expected: 2
        	            	actual  : 0
        	Test:       	TestVFS/TestScheme
        	Messages:   	list srcLoc location matching prefix
    backend_integration_test.go:405:
        	Error Trace:	backend_integration_test.go:405
        	            				backend_integration_test.go:118
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestVFS/TestScheme
        	Messages:   	list srcLoc location
    suite.go:63: test panicked: runtime error: index out of range [0] with length 0
        goroutine 8 [running]:
        runtime/debug.Stack(0xc0005593c8, 0x1c4ee60, 0xc0004e1040)
        	/Users/john.judd/.gvm/gos/go1.15.12/src/runtime/debug/stack.go:24 +0x9f
        github.com/stretchr/testify/suite.failOnPanic(0xc0003f4780)
        	/Users/john.judd/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:63 +0x57
        panic(0x1c4ee60, 0xc0004e1040)
        	/Users/john.judd/.gvm/gos/go1.15.12/src/runtime/panic.go:969 +0x1b9
        github.com/c2fo/vfs/v5/backend/testsuite.(*vfsTestSuite).Location(0xc0003f33c0, 0x1eac540, 0xc000441300)
        	/Users/john.judd/go/src/github.com/c2fo/vfs/backend/testsuite/backend_integration_test.go:406 +0x2d9e
        github.com/c2fo/vfs/v5/backend/testsuite.(*vfsTestSuite).TestScheme(0xc0003f33c0)
        	/Users/john.judd/go/src/github.com/c2fo/vfs/backend/testsuite/backend_integration_test.go:118 +0x15e
        reflect.Value.call(0xc0004792c0, 0xc000010f28, 0x13, 0x1cd89cf, 0x4, 0xc00008de30, 0x1, 0x1, 0xc00008dcf8, 0x100d88a, ...)
        	/Users/john.judd/.gvm/gos/go1.15.12/src/reflect/value.go:476 +0x8c7
        reflect.Value.Call(0xc0004792c0, 0xc000010f28, 0x13, 0xc00008de30, 0x1, 0x1, 0x3a, 0xc00007ce50, 0x1055e59)
        	/Users/john.judd/.gvm/gos/go1.15.12/src/reflect/value.go:337 +0xb9
        github.com/stretchr/testify/suite.Run.func1(0xc0003f4780)
        	/Users/john.judd/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:158 +0x379
        testing.tRunner(0xc0003f4780, 0xc000418d80)
        	/Users/john.judd/.gvm/gos/go1.15.12/src/testing/testing.go:1123 +0xef
        created by testing.(*T).Run
        	/Users/john.judd/.gvm/gos/go1.15.12/src/testing/testing.go:1168 +0x2b3
--- FAIL: TestVFS (2.89s)
    --- FAIL: TestVFS/TestScheme (2.89s)
FAIL
FAIL	github.com/c2fo/vfs/v5/backend/testsuite	3.348s
FAIL
```

### PR DESCRIPTION
**Pull request by funkyshu**
fixes #92 (broken by #72) where calling ListByPrefix() was fail from non-root locations when calling file-level prefixes like:
```go
	fs := gs.NewFileSystem()
	loc, _ := fs.NewLocation("mybucket", "/some/path/")
        filenamePrefix := "xyz"
        files, _ := loc.ListByPrefix(xyz)
```
Files used to always be empty.  This is now fixed and works in integration tests.  Also added to unit tests to cover this.

### CODE REVIEW

File: backend/testsuite/backend_integration_test.go [hunk 1]
```diff
@@ -111,7 +111,7 @@ func (s *vfsTestSuite) SetupSuite() {
 
 }
 
-//Test File
+// Test File
```
Comment (funkyshu) [inline backend/testsuite/backend_integration_test.go:114]: this was nothing but fixing linting

**Review by juanri0s — APPROVED** [review]

**Review by thatsmysky — APPROVED** [review]

**Review by dmcilvain44 — APPROVED** [review]
